apiVersion: v1
kind: Service
metadata:
  name: ia-production-system-service
spec:
  selector:
    app: ia-production-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
