apiVersion: v1
kind: Service
metadata:
  name: ia-agent-service
  labels:
    app: ia-enterprise-agent
spec:
  type: ClusterIP
  selector:
    app: ia-enterprise-agent          # Debe coincidir con el label del Deployment
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
